const test = require("node:test");
const assert = require("node:assert/strict");
const { EventEmitter } = require("events");
const http = require("http");
const { BackendSupervisor, redact } = require("../electron/backend-supervisor");

function child(pid = 1234) { const value = new EventEmitter(); value.pid = pid; value.stdout = new EventEmitter(); value.stderr = new EventEmitter(); value.kills = []; value.kill = signal => { value.kills.push(signal); return true; }; return value; }
test("backend launch is loopback-only, has a trusted data root, and cannot duplicate", () => { const spawned = []; const supervisor = new BackendSupervisor({ entry: "C:\\program\\index.js", programRoot: "C:\\program", dataRoot: "C:\\customer", port: 43123, logFile: "C:\\customer\\logs\\backend.log", spawn: (...args) => { spawned.push(args); return child(); } }); supervisor.launch(); const options = spawned[0][2]; assert.equal(options.shell, undefined); assert.equal(options.env.LUCKY_HOST, "127.0.0.1"); assert.equal(options.env.LUCKY_DATA_ROOT, "C:\\customer"); assert.equal(options.env.PORT, "43123"); assert.throws(() => supervisor.launch(), { code: "BACKEND_DUPLICATE" }); });
test("readiness accepts only HTTP 200 and fails if owned backend exited", async t => { const original = http.get; t.after(() => { http.get = original; }); const supervisor = new BackendSupervisor({ readinessTimeoutMs: 20 }); supervisor.child = child(); http.get = (_options, callback) => { const request = new EventEmitter(); request.destroy = error => request.emit("error", error); process.nextTick(() => callback({ statusCode: 200, resume() {} })); return request; }; await assert.doesNotReject(supervisor.waitUntilReady()); assert.equal(supervisor.ready, true); supervisor.child = null; await assert.rejects(supervisor.waitUntilReady(), { code: "BACKEND_EXITED_BEFORE_READY" }); });
test("readiness timeout fails closed and never reports ready", async t => { const original = http.get; t.after(() => { http.get = original; }); let now = 0; const supervisor = new BackendSupervisor({ readinessTimeoutMs: 1, now: () => ++now }); supervisor.child = child(); http.get = () => { const request = new EventEmitter(); request.destroy = () => {}; process.nextTick(() => request.emit("error", Object.assign(new Error("refused"), { code: "ECONNREFUSED" }))); return request; }; await assert.rejects(supervisor.waitUntilReady(), { code: "BACKEND_READINESS_TIMEOUT" }); assert.equal(supervisor.ready, false); });
test("restart circuit breaker permits only three attempts per five-minute window", () => { let now = 1000; const supervisor = new BackendSupervisor({ now: () => now, maxRestarts: 3, restartWindowMs: 300000 }); assert.equal(supervisor.canRestart(), true); assert.equal(supervisor.canRestart(), true); assert.equal(supervisor.canRestart(), true); assert.equal(supervisor.canRestart(), false); now += 300001; assert.equal(supervisor.canRestart(), true); });
test("graceful shutdown signals and force-kills only its owned child", async () => { const supervisor = new BackendSupervisor(); const owned = child(42); supervisor.child = owned; supervisor.ownedPid = 42; const stopping = supervisor.stop(10); assert.deepEqual(owned.kills, ["SIGTERM"]); owned.emit("exit", 0); assert.equal(await stopping, true); const foreign = child(99); supervisor.child = foreign; supervisor.ownedPid = 42; assert.equal(await supervisor.stop(1), false); assert.deepEqual(foreign.kills, []); });
test("forced termination is bounded to owned PID", async () => { const supervisor = new BackendSupervisor(); const owned = child(42); supervisor.child = owned; supervisor.ownedPid = 42; assert.equal(await supervisor.stop(1), false); assert.deepEqual(owned.kills, ["SIGTERM", "SIGKILL"]); });
test("backend operational log redaction removes credential material", () => { const value = redact("password=hunter2 setupCode=ABCD sessionToken=secret X-Lucky-Device-Key:key"); assert.doesNotMatch(value, /hunter2|ABCD|secret|:key/); assert.match(value, /\[REDACTED\]/); });
