const test = require("node:test");
const assert = require("node:assert/strict");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { HardwareUsbRecoveryService } = require("../services/hardware-usb-recovery-service");
const { HardwareService } = require("../services/hardware-service");

function rotationFixture(overrides={}) { const device={id:"hw-1",deviceId:"LRC-ABC",relayCount:4,credentialStatus:"REAUTHENTICATION_REQUIRED"},repository={list:()=>[device],findById:id=>id===device.id?device:null,update:(id,data)=>Object.assign(device,data)},hardware={getRequired:()=>device,getAuthenticated:()=>device,updateDiscoveredLocation(){}},transport={candidate:null,request(_port,payload){if(payload.command==="IDENTIFY")return{ok:true,deviceId:device.deviceId,relayCount:4};if(payload.command==="GET_RELAY_SAFETY")return{ok:true,deviceId:device.deviceId,relayCount:4,safe:true,activeChannels:[]};if(payload.command==="STAGE_DEVICE_KEY"){this.candidate=payload.deviceKey;return{ok:true,deviceId:device.deviceId,relayCount:4};}if(payload.command==="VERIFY_DEVICE_KEY")return{ok:true,deviceId:device.deviceId,relayCount:4,proof:crypto.createHmac("sha256",this.candidate).update(`${payload.nonce}|${device.deviceId}|4|${payload.transitionId}`).digest("hex")};if(payload.command==="COMMIT_DEVICE_KEY")return{ok:true,deviceId:device.deviceId,relayCount:4};return{ok:true};}};const service=new HardwareUsbRecoveryService({hardwareService:hardware,repository,transport:overrides.transport||transport,portProvider:{list:()=>[{port:"COM7"}]},discovery:{},randomBytes:size=>Buffer.alloc(size,7),now:()=>1000,audit:()=>{}});return{service,device,repository,transport}; }
test("USB Setup Code key rotation verifies nonce/HMAC, commits vault-facing record, and never returns key", async()=>{const f=rotationFixture(),token=f.service.issueToken("hw-1","owner").recoveryToken,result=await f.service.startKeyRotation({recoveryToken:token,port:"COM7",setupCode:"2345-6789-ABCD"},"owner");assert.equal(result.state,"COMPLETED");assert.equal(f.device.credentialStatus,"AUTHENTICATED");assert.doesNotMatch(JSON.stringify(result),/deviceKey|newKey|2345-6789-ABCD/);});
test("token is actor-bound and single use", async()=>{const f=rotationFixture(),token=f.service.issueToken("hw-1","owner").recoveryToken;await assert.rejects(f.service.startKeyRotation({recoveryToken:token,port:"COM7",setupCode:"2345"},"other"),{code:"USB_RECOVERY_TOKEN_INVALID"});await assert.rejects(f.service.startKeyRotation({recoveryToken:token,port:"COM7",setupCode:"2345"},"owner"),{code:"USB_RECOVERY_TOKEN_INVALID"});});
test("Relay ON blocks before staging and reports active channels", async()=>{const f=rotationFixture();f.transport.request=(port,payload)=>payload.command==="IDENTIFY"?{ok:true,deviceId:f.device.deviceId,relayCount:4}:{ok:true,deviceId:f.device.deviceId,relayCount:4,safe:false,activeChannels:[2]};const token=f.service.issueToken("hw-1","owner").recoveryToken;await assert.rejects(f.service.startKeyRotation({recoveryToken:token,port:"COM7",setupCode:"2345"},"owner"),error=>error.code==="RELAY_SAFE_STATE_CONFLICT"&&error.activeChannels[0]===2);});
test("firmware contract is fixed, bounded, rollback-capable and contains no Relay mutation",()=>{const root=path.resolve(__dirname,".."),source=fs.readFileSync(path.join(root,"firmware/src/serial/SerialRecoveryService.cpp"),"utf8"),header=fs.readFileSync(path.join(root,"firmware/src/serial/SerialRecoveryService.h"),"utf8");for(const command of ["IDENTIFY","GET_RELAY_SAFETY","STAGE_WIFI","VERIFY_TRANSITION","COMMIT_WIFI","ROLLBACK_WIFI","GET_TRANSITION_STATUS","STAGE_DEVICE_KEY","VERIFY_DEVICE_KEY","COMMIT_DEVICE_KEY","ROLLBACK_DEVICE_KEY"])assert.match(source,new RegExp(command));assert.match(header,/kMaximumPayload\s*=\s*768/);assert.match(header,/kTransactionTimeoutMs\s*=\s*120000/);assert.doesNotMatch(source,/turnOn|turnOff|turnAllOff|digitalWrite/);assert.match(source,/UNKNOWN_COMMAND/);});
test("atomic replacement moves mappings, archives old controller, and preserves identities",async()=>{const devices=[{id:"old",deviceId:"LRC-OLD",apiKey:"x".repeat(40),relayCount:4,status:"ONLINE"},{id:"new",deviceId:"LRC-NEW",apiKey:"y".repeat(40),relayCount:4,status:"ONLINE"}],tables=[{id:1,hardwareDeviceId:"old",relayChannel:1}],repository={list:()=>devices,findById:id=>devices.find(x=>x.id===id),mutateAtomically:work=>work(devices)},driver={relays:async()=>({relays:[{channel:1,state:"OFF"}]})};const service=new HardwareService(repository,driver,{tables:()=>tables,saveTables:()=>{},audit:()=>{}});const result=await service.replaceController("old","new",true,"owner");assert.equal(result.mappingCount,1);assert.equal(tables[0].hardwareDeviceId,"new");assert.equal(devices[0].status,"REPLACED_ARCHIVED");assert.equal(devices[0].deviceId,"LRC-OLD");assert.equal(devices[1].deviceId,"LRC-NEW");});
test("replacement rejects relay-count mismatch before mapping mutation",async()=>{const devices=[{id:"old",deviceId:"LRC-OLD",apiKey:"x".repeat(40),relayCount:8},{id:"new",deviceId:"LRC-NEW",apiKey:"y".repeat(40),relayCount:2}],tables=[{id:1,hardwareDeviceId:"old",relayChannel:4}],repository={list:()=>devices,findById:id=>devices.find(x=>x.id===id)},service=new HardwareService(repository,{},{tables:()=>tables,saveTables:()=>{}});await assert.rejects(service.replaceController("old","new",true,"owner"),{code:"RELAY_COUNT_MISMATCH"});assert.equal(tables[0].hardwareDeviceId,"old");});
