const test = require("node:test");
const assert = require("node:assert/strict");
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { HardwareUsbAdoptionService } = require("../services/hardware-usb-adoption-service");
const { HardwareWizardError } = require("../domain/hardware-wizard-error");
const { WindowsSerialRecoveryTransport } = require("../drivers/windows-serial-recovery-transport");

const identity = { ok:true, deviceId:"LRC-88A4750FF0A4", firmwareVersion:"1.2.0", apiVersion:"1", relayCount:4, boardTarget:"esp32" };
function fixture({ records=[], unsafe=false, badProof=false, saveFails=false, now=1000, transportFailure=null }={}) {
  const draft={id:"hwd-1",actorId:"owner",step:"AUTHENTICATION",candidate:{ipAddress:"192.168.1.193",port:80},verification:{...identity,success:true,relays:[]}};
  const commands=[], saved=[], logs=[]; let candidateKey, transitionId, randomCalls=0;
  const transport={request(port,payload){commands.push({port,payload:{...payload,deviceKey:payload.deviceKey?"[SECRET]":undefined,setupCode:payload.setupCode?"[SECRET]":undefined}});if(transportFailure?.command===payload.command)throw Object.assign(Error(transportFailure.message||"raw serial secret"),transportFailure);if(payload.command==="IDENTIFY")return identity;if(payload.command==="GET_RELAY_SAFETY")return{...identity,safe:!unsafe,activeChannels:unsafe?[2]:[]};if(payload.command==="STAGE_DEVICE_KEY"){candidateKey=payload.deviceKey;transitionId=payload.transitionId;return{ok:true};}if(payload.command==="VERIFY_DEVICE_KEY"){const proof=crypto.createHmac("sha256",candidateKey).update(`${payload.nonce}|${identity.deviceId}|4|${transitionId}`).digest("hex");return{...identity,transitionId,proof:badProof?"0".repeat(64):proof};}if(payload.command==="COMMIT_DEVICE_KEY")return{ok:true};if(payload.command==="ROLLBACK_DEVICE_KEY")return{ok:true};throw Error("unexpected command");}};
  const repository={list:()=>records,findById:id=>saved.find(x=>x.id===id)||null};
  const hardwareService={repository,commitUsbAdoption(verified,key,metadata){if(saveFails)throw Object.assign(Error("vault"),{code:"VAULT_COMMIT_FAILED"});const record={id:"hw-new",...verified,...metadata,apiKey:key};saved.push(record);return{id:record.id,deviceId:record.deviceId,relayCount:record.relayCount};}};
  const wizardService={get:id=>{if(id!==draft.id)throw new HardwareWizardError("OPERATION_CANCELLED","missing",404);return draft;},completeUsbAdoption(id,record){draft.step="RELAY_TEST";draft.apiKey=record.apiKey;return{step:draft.step};}};
  const service=new HardwareUsbAdoptionService({wizardService,hardwareService,repository,driver:{verifyDevice:async()=>({success:true,verified:true,deviceId:identity.deviceId,relayCount:4,firmwareVersion:"1.2.0",apiVersion:"1"})},transport,portProvider:{list:()=>[{port:"COM3"}]},randomBytes:size=>{randomCalls++;return Buffer.alloc(size,7);},now:()=>now,log:(level,event,details)=>logs.push({level,event,...details})});
  return{service,draft,commands,saved,logs,getKey:()=>candidateKey,getRandomCalls:()=>randomCalls};
}
async function begin(f, overrides={}) { const token=f.service.issueToken("hwd-1","COM3","owner","session-a").adoptionToken;return f.service.start("hwd-1",{adoptionToken:token,port:"COM3",setupCode:"ABCD-EFGH-JKMN",deviceName:"กล่องควบคุมโต๊ะ",location:"โซนหลัก",confirmedSafe:true,...overrides},"owner","session-a"); }

test("unknown discovered device completes transactional USB adoption without exposing secrets",async()=>{const f=fixture(),result=await begin(f);assert.equal(result.state,"COMPLETED");assert.equal(f.draft.step,"RELAY_TEST");assert.equal(f.saved.length,1);assert.equal(f.saved[0].deviceId,identity.deviceId);assert.equal(Object.hasOwn(result,"newKey"),false);assert.equal(Object.hasOwn(result,"transitionId"),false);assert.equal(JSON.stringify(result).includes(f.getKey()),false);assert.equal(f.commands.some(x=>x.payload.command==="STAGE_DEVICE_KEY"),true);assert.equal(f.commands.some(x=>x.payload.command==="ROLLBACK_DEVICE_KEY"),false);});
test("candidate key is generated from 32 CSPRNG bytes and browser request has no identity",async()=>{const f=fixture();await begin(f);assert.ok(Buffer.from(f.getKey(),"base64url").length>=32);const source=fs.readFileSync(path.join(__dirname,"../public/js/phase5_5-defect-fix.js"),"utf8");assert.doesNotMatch(source,/deviceId\s*:/);assert.doesNotMatch(source,/apiKey\s*:/);assert.match(source,/setupCode, deviceName, location, confirmedSafe/);});
test("token is bound to draft actor session COM, expires and is single use",async()=>{const f=fixture();const token=f.service.issueToken("hwd-1","COM3","owner","session-a").adoptionToken;await assert.rejects(()=>f.service.start("hwd-1",{adoptionToken:token,port:"COM3",setupCode:"ABCD-EFGH-JKMN",deviceName:"x",location:"",confirmedSafe:true},"owner","session-b"),/หมดอายุ|ถูกใช้/);await assert.rejects(()=>f.service.start("hwd-1",{adoptionToken:token,port:"COM3",setupCode:"ABCD-EFGH-JKMN",deviceName:"x",location:"",confirmedSafe:true},"owner","session-a"),/หมดอายุ|ถูกใช้/);});
test("arbitrary browser identity and credential fields are rejected",async()=>{const f=fixture();const token=f.service.issueToken("hwd-1","COM3","owner","session-a").adoptionToken;await assert.rejects(()=>f.service.start("hwd-1",{adoptionToken:token,port:"COM3",setupCode:"ABCD-EFGH-JKMN",deviceName:"x",location:"",confirmedSafe:true,deviceId:"attacker",apiKey:"secret"},"owner","session-a"),/ไม่ได้รับอนุญาต/);});
test("discovery identity mismatch is rejected before token issuance",()=>{const f=fixture();f.draft.verification.deviceId="LRC-OTHER";assert.throws(()=>f.service.issueToken("hwd-1","COM3","owner","session-a"),/ไม่ตรง/);});
test("duplicate and reauthentication records fail closed",()=>{const duplicate=fixture({records:[{deviceId:identity.deviceId,credentialStatus:"AUTHENTICATED"}]});assert.throws(()=>duplicate.service.issueToken("hwd-1","COM3","owner","s"),/มีอยู่/);const reauth=fixture({records:[{deviceId:identity.deviceId,credentialStatus:"REAUTHENTICATION_REQUIRED"}]});assert.throws(()=>reauth.service.issueToken("hwd-1","COM3","owner","s"),/record เดิม/);});
test("relay ON is reported and no all-off command is ever sent",()=>{const f=fixture({unsafe:true});assert.throws(()=>f.service.issueToken("hwd-1","COM3","owner","s"),/Relay ช่อง 2/);assert.equal(f.commands.some(x=>/OFF|SET_RELAY/.test(x.payload.command)&&x.payload.command!=="GET_RELAY_SAFETY"),false);});
test("invalid Setup Code fails and correct code is never returned or logged",async()=>{const f=fixture();await assert.rejects(()=>begin(f,{setupCode:"OOOO-OOOO-OOOO"}),/Setup Code/);const all=JSON.stringify({commands:f.commands});assert.doesNotMatch(all,/ABCD-EFGH-JKMN|OOOO-OOOO-OOOO/);});
test("bad HMAC proof rolls firmware candidate back and creates no record",async()=>{const f=fixture({badProof:true}),result=await begin(f);assert.equal(result.state,"FAILED");assert.equal(f.saved.length,0);assert.equal(f.commands.some(x=>x.payload.command==="ROLLBACK_DEVICE_KEY"),true);});
test("vault failure retains the same memory key for bounded retry",async()=>{const f=fixture({saveFails:true}),result=await begin(f);assert.equal(result.state,"VAULT_RECOVERY_REQUIRED");const key=f.getKey();assert.ok(key);const retry=await f.service.retry(result.id,"owner","session-a");assert.equal(retry.state,"VAULT_RECOVERY_REQUIRED");assert.equal(f.getKey(),key);assert.equal(f.saved.length,0);});
test("server restart loses recovery key and fails closed",async()=>{const f=fixture({saveFails:true}),result=await begin(f);const fresh=fixture().service;await assert.rejects(()=>fresh.retry(result.id,"owner","session-a"),/ไม่พบงาน/);});
test("generic Wizard error gives precise Thai USB adoption guidance",()=>{const error=new HardwareWizardError("USB_REAUTHENTICATION_REQUIRED","missing",409);assert.equal(error.public().userMessage,"ยังไม่มีข้อมูลยืนยันกล่องนี้ในเครื่องคอมพิวเตอร์");assert.match(error.public().recoveryMessage,/USB/);});
test("UI never asks for Device Key and includes existing USB adoption action",()=>{const source=fs.readFileSync(path.join(__dirname,"../public/js/phase5_5-defect-fix.js"),"utf8");assert.match(source,/เพิ่มกล่องนี้ผ่าน USB/);assert.doesNotMatch(source,/wizardApiKey|lucky-relay-1234/);});
test("adoption routes require Hardware Admin, loopback and authenticated session binding",()=>{const source=fs.readFileSync(path.join(__dirname,"../index.js"),"utf8");for(const route of ["usb-adoption/token","usb-adoption/start","usb-adoption/:operationId\""])assert.match(source,new RegExp(route.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")));assert.match(source,/usb-adoption\/token[^\n]+requireHardwareAdmin, requireLoopback/);assert.match(source,/issueToken\([^\n]+tokenFromRequest\(req\)/);assert.match(source,/hardwareUsbAdoptionService\.retry\([^\n]+tokenFromRequest\(req\)/);});

for (const item of [
  ["IDENTIFY timeout", "IDENTIFY", "USB_SERIAL_TIMEOUT", "USB_IDENTIFY_TIMEOUT", "IDENTIFY"],
  ["GET_RELAY_SAFETY timeout", "GET_RELAY_SAFETY", "USB_SERIAL_TIMEOUT", "USB_RELAY_SAFETY_TIMEOUT", "GET_RELAY_SAFETY"],
  ["malformed serial response", "IDENTIFY", "USB_SERIAL_RESPONSE_INVALID", "USB_SERIAL_RESPONSE_INVALID", "IDENTIFY"],
  ["COM busy", "IDENTIFY", "USB_PORT_BUSY", "USB_PORT_BUSY", "IDENTIFY"]
]) test(`preflight maps ${item[0]} without creating candidate material`,()=>{const f=fixture({transportFailure:{command:item[1],code:item[2],status:item[2].includes("TIMEOUT")?504:409}});assert.throws(()=>f.service.issueToken("hwd-1","COM3","owner","session-a"),error=>error.code===item[3]);assert.equal(f.getRandomCalls(),0);assert.equal(f.commands.some(x=>x.payload.command==="STAGE_DEVICE_KEY"),false);const log=f.logs.at(-1);assert.equal(log.errorCode,item[3]);assert.equal(log.preflightStage,item[4]);assert.equal(log.port,"COM3");assert.equal(Object.hasOwn(log,"setupCode"),false);assert.equal(Object.hasOwn(log,"deviceKey"),false);assert.equal(Object.hasOwn(log,"adoptionToken"),false);assert.doesNotMatch(JSON.stringify(log),/raw serial secret/i);});

test("Windows serial transport returns actionable status and machine codes",()=>{const timeout=new WindowsSerialRecoveryTransport({platform:"win32",run:()=>({status:1,stderr:"response timeout"})});assert.throws(()=>timeout.request("COM3",{command:"IDENTIFY"}),error=>error.code==="USB_SERIAL_TIMEOUT"&&error.status===504);const busy=new WindowsSerialRecoveryTransport({platform:"win32",run:()=>({status:1,stderr:"Access denied: port is in use"})});assert.throws(()=>busy.request("COM3",{command:"IDENTIFY"}),error=>error.code==="USB_PORT_BUSY"&&error.status===409);const malformed=new WindowsSerialRecoveryTransport({platform:"win32",run:()=>({status:0,stdout:"not-json"})});assert.throws(()=>malformed.request("COM3",{command:"IDENTIFY"}),error=>error.code==="USB_SERIAL_RESPONSE_INVALID"&&error.status===502);});

test("UI keeps Setup Code until preflight succeeds and never calls start on preflight rejection",()=>{const source=fs.readFileSync(path.join(__dirname,"../public/js/phase5_5-defect-fix.js"),"utf8"),tokenCall=source.indexOf("/usb-adoption/token`"),clear=source.indexOf('code.value = ""',tokenCall),startCall=source.indexOf("/usb-adoption/start`",tokenCall);assert.ok(tokenCall>0&&clear>tokenCall&&startCall>clear);assert.match(source,/const issued = await api[\s\S]+code\.value = "";[\s\S]+const operation = await api/);});
