const test=require("node:test"),assert=require("node:assert/strict"),crypto=require("crypto"),fs=require("fs"),os=require("os"),path=require("path"),{EventEmitter}=require("events");
const {FirmwarePackageService,canonicalManifest}=require("../services/firmware-package-service");
const {PerDeviceNvsService}=require("../services/per-device-nvs-service");

function modernFixture(mode="test"){
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"lucky-pkg-")),{publicKey,privateKey}=crypto.generateKeyPairSync("ed25519");
  const entry=(role,file,offset)=>{const content=role||file;fs.writeFileSync(path.join(root,file),content);return{role,file,offset,sha256:crypto.createHash("sha256").update(content).digest("hex"),size:content.length};};
  const app=entry("application","firmware.bin","0x10000"),boot=entry("bootloader","bootloader.bin","0x1000"),part=entry("partitions","partitions.bin","0x8000"),tool=entry("tool","esptool.exe"),gen=entry("generator","lucky-nvs-generator.exe");tool.version="4.11.0";gen.version="test";
  const manifest={manifestFormatVersion:1,product:"Lucky Relay Controller",firmwareVersion:"1.1.0",buildId:"test-abc",releaseChannel:mode,signingEnvironment:mode,targetChip:"ESP32",boardProfile:"esp32dev-4mb",flashSizeBytes:4194304,flashMode:"dio",flashFrequency:"40m",esptool:tool,nvsGenerator:gen,distributionAssets:[],nvsPolicy:{schemaVersion:1,namespace:"lucky-relay",offset:"0x9000",size:"0x5000",keys:{},relayCounts:[2,4,8]},existingUpdate:{files:[app]},newInstall:{files:[boot,part,{role:"sessionNvs",offset:"0x9000"},app]}};
  fs.writeFileSync(path.join(root,"manifest.json"),canonicalManifest(manifest));fs.writeFileSync(path.join(root,"manifest.sig"),crypto.sign(null,canonicalManifest(manifest),privateKey).toString("base64"));return{root,manifest,publicKey:publicKey.export({type:"spki",format:"pem"}),privateKey};
}
function resign(f){fs.writeFileSync(path.join(f.root,"manifest.json"),canonicalManifest(f.manifest));fs.writeFileSync(path.join(f.root,"manifest.sig"),crypto.sign(null,canonicalManifest(f.manifest),f.privateKey).toString("base64"));}
test("canonical manifest is deterministic across object key order",()=>assert.equal(canonicalManifest({b:2,a:{d:4,c:3}}).toString(),canonicalManifest({a:{c:3,d:4},b:2}).toString()));
test("valid test package verifies and production rejects it",()=>{const f=modernFixture();assert.equal(new FirmwarePackageService({packageRoot:f.root,publicKey:f.publicKey,mode:"test"}).verify().manifest.buildId,"test-abc");assert.throws(()=>new FirmwarePackageService({packageRoot:f.root,publicKey:f.publicKey,mode:"production"}).verify(),e=>e.code==="TEST_PACKAGE_REJECTED");});
test("modified manifest, firmware, wrong key and missing signature fail",()=>{for(const kind of ["manifest","firmware","key","signature"]){const f=modernFixture();if(kind==="manifest")fs.writeFileSync(path.join(f.root,"manifest.json"),fs.readFileSync(path.join(f.root,"manifest.json"),"utf8").replace("test-abc","test-tampered"));if(kind==="firmware")fs.appendFileSync(path.join(f.root,"firmware.bin"),"x");if(kind==="signature")fs.rmSync(path.join(f.root,"manifest.sig"));const other=crypto.generateKeyPairSync("ed25519").publicKey.export({type:"spki",format:"pem"});assert.throws(()=>new FirmwarePackageService({packageRoot:f.root,publicKey:kind==="key"?other:f.publicKey,mode:"test"}).verify());}});
test("private key is absent from package",()=>{const f=modernFixture();assert.equal(fs.readdirSync(f.root).some(name=>/private|\.key$|\.pem$/i.test(name)),false);});
test("invalid target, flash size, channel and absolute path fail closed",()=>{for(const mutate of [m=>m.targetChip="ESP32-S3",m=>m.flashSizeBytes=8388608,m=>m.releaseChannel="production",m=>m.existingUpdate.files[0].file="C:\\firmware.bin"]){const f=modernFixture();mutate(f.manifest);resign(f);assert.throws(()=>new FirmwarePackageService({packageRoot:f.root,publicKey:f.publicKey,mode:"test"}).verify());}});
test("duplicate files, duplicate offsets, invalid signature encoding and unexpected files fail",()=>{for(const kind of ["file","offset","signature","unexpected"]){const f=modernFixture();if(kind==="file")f.manifest.existingUpdate.files.push({...f.manifest.existingUpdate.files[0],offset:"0x11000"});if(kind==="offset")f.manifest.newInstall.files[1].offset="0x1000";if(kind==="signature")fs.writeFileSync(path.join(f.root,"manifest.sig"),"not-base64");else resign(f);if(kind==="unexpected")fs.writeFileSync(path.join(f.root,"secret.bin"),"x");assert.throws(()=>new FirmwarePackageService({packageRoot:f.root,publicKey:f.publicKey,mode:"test"}).verify());}});
function fakeGenerator({fail=false,size=0x5000,capture=[]}={}){return(tool,args)=>{capture.push({tool,args});const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();process.nextTick(()=>{if(!fail)fs.writeFileSync(args[2],crypto.randomBytes(size));child.emit("close",fail?1:0);});return child;};}
test("NVS generation validates schema, image size and keeps secrets off command line",async()=>{const capture=[],service=new PerDeviceNvsService({spawnProcess:fakeGenerator({capture})}),result=await service.create({generatorPath:"approved.exe",operationId:"op1",relayCount:4});assert.equal(fs.statSync(result.path).size,0x5000);assert.match(result.setupCode,/^[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{4}(?:-[23456789ABCDEFGHJKMNPQRSTUVWXYZ]{4}){2}$/);assert.equal(capture[0].args.some(value=>String(value).includes(result.setupCode.replaceAll("-",""))||String(value).includes(result.deviceKey)),false);assert.equal(service.verify("op1").offset,"0x9000");service.cleanup("op1");assert.equal(fs.existsSync(result.path),false);});
test("NVS generator rejects relay count, bad size and failure with cleanup",async()=>{for(const scenario of [{relayCount:3,spawn:fakeGenerator()},{relayCount:4,spawn:fakeGenerator({size:10})},{relayCount:4,spawn:fakeGenerator({fail:true})}]){const service=new PerDeviceNvsService({spawnProcess:scenario.spawn});await assert.rejects(()=>service.create({generatorPath:"approved.exe",operationId:crypto.randomUUID(),relayCount:scenario.relayCount}));}});
test("different sessions produce different secrets and images",async()=>{const service=new PerDeviceNvsService({spawnProcess:fakeGenerator()}),a=await service.create({generatorPath:"approved.exe",operationId:"a",relayCount:2}),b=await service.create({generatorPath:"approved.exe",operationId:"b",relayCount:2});assert.notEqual(a.deviceKey,b.deviceKey);assert.notEqual(a.setupCode,b.setupCode);assert.notEqual(a.sha256,b.sha256);service.cleanup("a");service.cleanup("b");});
test("secure RNG failure fails before generator execution",async()=>{let started=false;const service=new PerDeviceNvsService({spawnProcess:()=>{started=true;},randomBytes:()=>{throw Error("rng");}});await assert.rejects(()=>service.create({generatorPath:"approved.exe",operationId:"rng",relayCount:4}),e=>e.code==="SECURE_RANDOM_UNAVAILABLE");assert.equal(started,false);});
test("Lucky-built generator produces exact 0x5000 image without installed Python",async()=>{const executable=path.join(__dirname,"..","tools","phase5_1","dist","lucky-nvs-generator.exe");assert.ok(fs.existsSync(executable));const service=new PerDeviceNvsService(),result=await service.create({generatorPath:executable,operationId:"real-generator",relayCount:4});assert.equal(fs.statSync(result.path).size,0x5000);assert.equal(service.verify("real-generator").sha256,result.sha256);service.cleanup("real-generator");});
test("firmware has no bootstrap secrets and update has no erase command",()=>{const binary=fs.readFileSync(path.join(__dirname,"..","firmware",".pio","build","esp32dev","firmware.bin"));for(const secret of ["TinTin_2.4G","0979269904","lucky-relay-1234"])assert.equal(binary.includes(Buffer.from(secret)),false);assert.doesNotMatch(fs.readFileSync(path.join(__dirname,"..","services","usb-flasher-service.js"),"utf8"),/erase_flash/);});
