const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { LegacyDataHandoffService, MIGRATION_ID, REQUIRED } = require("../services/legacy-data-handoff-service");

function fixture(t) { const base = fs.mkdtempSync(path.join(os.tmpdir(), "lucky-6a-migrate-")); t.after(() => fs.rmSync(base, { recursive: true, force: true })); return { base, source: path.join(base, "app", "data"), destination: path.join(base, "customer") }; }
function seed(source, options = {}) { fs.mkdirSync(source, { recursive: true }); const store = options.badSchema ? {} : { tables: [], members: [], products: [], bills: [], payments: [], secretProbe: "device-key-must-not-enter-manifest" }; fs.writeFileSync(path.join(source, "store.json"), options.invalidJson ? "{" : JSON.stringify(store)); for (const name of REQUIRED.slice(1)) fs.writeFileSync(path.join(source, name), "[]"); fs.mkdirSync(path.join(source, "backups")); fs.writeFileSync(path.join(source, "backups", "backup-safe.json"), "{}"); }

test("no legacy data is detected without creating migration output", t => { const f = fixture(t), service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); assert.equal(service.detect().status, "NO_LEGACY_DATA"); assert.equal(fs.existsSync(f.destination), false); });
test("invalid JSON and schema are rejected before copying", t => { const a = fixture(t); seed(a.source, { invalidJson: true }); assert.equal(new LegacyDataHandoffService({ sourceRoot: a.source, destinationRoot: a.destination }).detect().status, "LEGACY_DATA_INVALID"); const b = fixture(t); seed(b.source, { badSchema: true }); assert.equal(new LegacyDataHandoffService({ sourceRoot: b.source, destinationRoot: b.destination }).detect().status, "LEGACY_DATA_INVALID"); });
test("valid legacy data is copied, verified, committed and source remains", t => { const f = fixture(t); seed(f.source); const service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); const before = service.manifest(f.source); const result = service.migrate(); assert.equal(result.marker.status, "COMPLETED"); assert.equal(service.manifestDestination().sha256, before.sha256); assert.equal(fs.existsSync(path.join(f.source, "store.json")), true); assert.equal(service.detect().status, "MIGRATION_ALREADY_COMPLETE"); assert.equal(fs.readdirSync(path.join(f.destination, "migration")).some(name => name.startsWith(".recovery-")), true); });
test("manifest and logs contain hashes and metadata, never record contents", t => { const f = fixture(t), events = []; seed(f.source); const service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination, log: (...args) => events.push(args) }); service.migrate(); const artifacts = fs.readdirSync(path.join(f.destination, "migration")).filter(x => x.endsWith(".json")).map(x => fs.readFileSync(path.join(f.destination, "migration", x), "utf8")).join("\n"); assert.doesNotMatch(artifacts + JSON.stringify(events), /device-key-must-not-enter-manifest/); assert.match(artifacts, /sourceManifestSha256/); });
test("hash mismatch fails before activation and does not create an empty store", t => { const f = fixture(t); seed(f.source); class TamperingService extends LegacyDataHandoffService { copyManifest(manifest, staging) { super.copyManifest(manifest, staging); fs.appendFileSync(path.join(staging, "database", "store.json"), " "); } } const service = new TamperingService({ sourceRoot: f.source, destinationRoot: f.destination }); assert.throws(() => service.migrate(), { code: "MIGRATION_HASH_MISMATCH" }); assert.equal(fs.existsSync(path.join(f.destination, "database", "store.json")), false); assert.equal(fs.existsSync(path.join(f.source, "store.json")), true); assert.notEqual(service.detect().status, "MIGRATION_ALREADY_COMPLETE"); });
test("existing destination and unsafe source entry fail closed", t => { const f = fixture(t); seed(f.source); fs.mkdirSync(path.join(f.destination, "database"), { recursive: true }); fs.writeFileSync(path.join(f.destination, "database", "existing.json"), "{}"); const service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); assert.equal(service.detect().status, "LEGACY_DATA_AMBIGUOUS"); assert.throws(() => service.migrate(), { code: "LEGACY_DATA_AMBIGUOUS" }); assert.equal(fs.readFileSync(path.join(f.destination, "database", "existing.json"), "utf8"), "{}"); });
test("incomplete activation resumes from recovery and commits idempotently", t => { const f = fixture(t); seed(f.source); class InterruptedService extends LegacyDataHandoffService { activateDirectory(directory, staging, manifest) { super.activateDirectory(directory, staging, manifest); if (directory === "database" && !this.failed) { this.failed = true; throw Object.assign(new Error("simulated power loss"), { code: "SIMULATED_POWER_LOSS" }); } } } const interrupted = new InterruptedService({ sourceRoot: f.source, destinationRoot: f.destination }); assert.throws(() => interrupted.migrate(), { code: "SIMULATED_POWER_LOSS" }); assert.equal(interrupted.detect().status, "MIGRATION_INCOMPLETE"); assert.equal(fs.existsSync(path.join(f.destination, "migration", `${MIGRATION_ID}.json`)), false); const resumed = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); assert.equal(resumed.migrate().marker.status, "COMPLETED"); assert.equal(resumed.migrate().status, "MIGRATION_ALREADY_COMPLETE"); });
test("only exact legacy data root is considered; pre-production archive is ignored", t => { const f = fixture(t); const archive = path.join(f.base, "output", "pre-production-archive-2026"); seed(archive); const service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); assert.equal(service.detect().status, "NO_LEGACY_DATA"); assert.equal(fs.existsSync(archive), true); });
test("hardware secret vault under config is migrated alongside device records", t => { const f = fixture(t); seed(f.source); const vault = { schemaVersion: 1, protection: "DPAPI_CURRENT_USER", secrets: { "hws-1": { ciphertext: "opaque-dpapi-blob", createdAt: new Date().toISOString() } } }; fs.mkdirSync(path.join(f.source, "config"), { recursive: true }); fs.writeFileSync(path.join(f.source, "config", "hardware-secrets.dpapi.json"), JSON.stringify(vault)); const service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); const result = service.migrate(); assert.equal(result.marker.status, "COMPLETED"); const migrated = JSON.parse(fs.readFileSync(path.join(f.destination, "config", "hardware-secrets.dpapi.json"), "utf8")); assert.deepEqual(migrated, vault); });
test("legacy data without a hardware secret vault still migrates cleanly", t => { const f = fixture(t); seed(f.source); const service = new LegacyDataHandoffService({ sourceRoot: f.source, destinationRoot: f.destination }); const result = service.migrate(); assert.equal(result.marker.status, "COMPLETED"); assert.equal(fs.existsSync(path.join(f.destination, "config")), false); });
