const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { HardwareSecretVault } = require("../services/hardware-secret-vault");
const { HardwareRepository } = require("../repositories/hardware-repository");
const { PortableMigrationService, portableDigest } = require("../services/portable-migration-service");

const SECRET = "unique-device-key-that-is-longer-than-thirty-two-bytes";
class Protector { protect(value){return Buffer.from(value).toString("base64");} unprotect(value){return Buffer.from(value,"base64").toString();} }
function fixture(t) { const root=fs.mkdtempSync(path.join(os.tmpdir(),"lucky-55-vault-"));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));return{root,records:path.join(root,"database","hardware-devices.json"),vault:path.join(root,"config","hardware-secrets.dpapi.json")}; }
test("plaintext Hardware Device Key migrates transactionally to a secret reference", t => { const f=fixture(t);fs.mkdirSync(path.dirname(f.records),{recursive:true});fs.writeFileSync(f.records,JSON.stringify([{id:"hw-1",deviceId:"LRC-A",apiKey:SECRET,relayCount:4}]));const vault=new HardwareSecretVault({file:f.vault,protector:new Protector(),randomUUID:()=>"secret-1"});const repository=new HardwareRepository(f.records,{secretVault:vault});assert.equal(repository.findById("hw-1").apiKey,SECRET);const disk=fs.readFileSync(f.records,"utf8");assert.doesNotMatch(disk,/apiKey|unique-device-key/);assert.match(disk,/secretId/);assert.doesNotMatch(fs.readFileSync(f.vault,"utf8"),/unique-device-key/); });
test("missing or undecryptable vault reference fails closed", t => { const f=fixture(t);fs.mkdirSync(path.dirname(f.records),{recursive:true});fs.writeFileSync(f.records,JSON.stringify([{id:"hw-1",deviceId:"LRC-A",secretId:"missing"}]));const vault=new HardwareSecretVault({file:f.vault,protector:new Protector()});assert.throws(()=>new HardwareRepository(f.records,{secretVault:vault}),{code:"HARDWARE_SECRET_MISSING"}); });
test("reauthentication-required imported record is allowed without a local secret", t => { const f=fixture(t);fs.mkdirSync(path.dirname(f.records),{recursive:true});fs.writeFileSync(f.records,JSON.stringify([{id:"hw-1",deviceId:"LRC-A",credentialStatus:"REAUTHENTICATION_REQUIRED"}]));const vault=new HardwareSecretVault({file:f.vault,protector:new Protector()});const repository=new HardwareRepository(f.records,{secretVault:vault});assert.equal(repository.findById("hw-1").apiKey,undefined); });
test("portable export strips DPAPI references and keys and forces reauthentication", () => { const hardware={list:()=>[{id:"hw-1",deviceId:"LRC-A",secretId:"hws-1",apiKey:SECRET,relayCount:4,status:"ONLINE"}]};const service=new PortableMigrationService({getStore:()=>({tables:[]}),reservations:{list:()=>[]},deposits:{list:()=>[]},hardwareRepository:hardware});const bundle=service.exportBundle("owner");const text=JSON.stringify(bundle);assert.doesNotMatch(text,/apiKey|secretId|ciphertext|unique-device-key/);assert.equal(bundle.payload.hardware[0].credentialStatus,"REAUTHENTICATION_REQUIRED");assert.equal(service.validate(bundle),true); });
test("portable bundle tampering, secret material, and duplicate identities fail closed", () => { const service=new PortableMigrationService({});const payload={store:{tables:[]},reservations:[],reservationDeposits:[],hardware:[{deviceId:"LRC-A"},{deviceId:"LRC-A"}]};const duplicate={schema:"lucky-portable-migration-v1",payload,sha256:portableDigest(payload)};assert.throws(()=>service.validate(duplicate),{code:"PORTABLE_DEVICE_ID_AMBIGUOUS"});const secretPayload={store:{tables:[]},reservations:[],reservationDeposits:[],hardware:[{deviceId:"LRC-A",apiKey:SECRET}]};assert.throws(()=>service.validate({schema:"lucky-portable-migration-v1",payload:secretPayload,sha256:portableDigest(secretPayload)}),{code:"PORTABLE_BUNDLE_SECRET_REJECTED"}); });
