const assert = require("assert");
const { JsonUserRepository } = require("../repositories/json-user-repository");
const { AuthService } = require("../services/auth-service");
const { PERMISSIONS, hasPermission } = require("../domain/permissions");
const store = {};
const repository = new JsonUserRepository({ getStore: () => store, save: () => {} });
const auth = new AuthService(repository, () => new Date("2026-07-26T00:00:00.000Z"));
const admin = auth.bootstrap(); assert.strictEqual(admin.username, "admin"); assert.ok(admin.passwordHash.startsWith("scrypt$")); assert.strictEqual(auth.bootstrap(), null);
const login = auth.login("admin", "123456789"); assert.strictEqual(login.user.role, "OWNER"); assert.strictEqual(auth.current(login.token).userId, "admin");
assert.throws(() => auth.login("admin", "wrong"), /Invalid/);
repository.add({ userId:"disabled", username:"disabled", passwordHash:admin.passwordHash, displayName:"Disabled", role:"STAFF", status:"DISABLED", createdAt:"", updatedAt:"" });
assert.throws(() => auth.login("disabled", "123456789"), /disabled/);
assert.strictEqual(hasPermission("OWNER", PERMISSIONS.BILL_VOID), true);
assert.strictEqual(hasPermission("MANAGER", PERMISSIONS.BILL_VOID), true);
assert.strictEqual(hasPermission("CASHIER", PERMISSIONS.BILL_VOID), false);
assert.strictEqual(hasPermission("CASHIER", PERMISSIONS.PAYMENT_CONFIRM), true);
assert.strictEqual(hasPermission("STAFF", PERMISSIONS.TABLE_PAUSE), true);
assert.strictEqual(hasPermission("STAFF", PERMISSIONS.PAYMENT_CONFIRM), false);
auth.logout(login.token); assert.strictEqual(auth.current(login.token), null);
const restored=JSON.parse(JSON.stringify(store)); assert.strictEqual(restored.users.length,2); assert.ok(!JSON.stringify(restored).includes('"password":"ChangeMe123!"'));
console.log("Sprint 5 authentication and permissions tests passed");
