const assert = require("assert");
const { JsonMemberRepository } = require("../repositories/json-member-repository");
const { MemberService } = require("../services/member-service");
const { normalizeSettings } = require("../services/settings-service");

const store = { members: [], memberPointTransactions: [] };
const service = new MemberService(new JsonMemberRepository({ getStore: () => store, save: () => {} }));
const member = service.create({ memberCode: "M9B", displayName: "Reward Member" }, "owner");
member.points = 300;
const settings = normalizeSettings({ hourlyRate: 100, minimumCharge: 0, tableCount: 1 });
assert.doesNotThrow(() => ({ memberId: null, redeemedPoints: 0 }), "guest/no-redeem input is intentionally a no-op");
const bill = { id: "reward-bill", memberId: member.id, saleSource: "TABLE", playDurationSeconds: 14400, status: "awaiting_payment", totalSatang: 50000, total: 500 };
const max = service.calculateMaximumRedeem(member, bill, settings);
assert.strictEqual(max.maximumPoints, 300);
const preview = service.previewRedeem(bill, 100, settings);
assert.strictEqual(preview.valueSatang, 10000);
assert.strictEqual(preview.netTotalSatang, 40000);
service.selectRedeem(bill, 100, settings, "cashier");
assert.strictEqual(bill.total, 400);
service.redeemPoints(bill, "cashier");
assert.strictEqual(member.points, 200);
service.earn(bill, "cashier", settings);
assert.strictEqual(bill.pointsEarned, 20, "earn must use net total");
assert.strictEqual(member.points, 220);
service.rollbackRedeem(bill, "owner");
service.void(bill, "owner");
assert.strictEqual(member.points, 300, "void returns both redeemed and earned points exactly once");
assert.strictEqual(service.redeemPoints({ memberId: null, redeemSelected: false }, "cashier"), null, "no-redeem bills do not call member logic");
assert.throws(() => service.previewRedeem({ ...bill, id: "too-much", status: "awaiting_payment", totalSatang: 10000, total: 100, redeemedPoints: 0 }, 101, settings), /Insufficient/);
assert.throws(() => service.previewRedeem({ ...bill, id: "minimum", status: "awaiting_payment", totalSatang: 50000, total: 500 }, 99, settings), /Minimum/);
console.log("Sprint 9B rewards and redemption tests passed");
