const test = require("node:test");
const assert = require("node:assert/strict");
const crypto = require("crypto");
const fs = require("fs");
const os = require("os");
const path = require("path");
const { EventEmitter } = require("events");
const { FirmwarePackageService, canonicalManifest } = require("../services/firmware-package-service");
const { UsbFlasherService } = require("../services/usb-flasher-service");

function signedPackage() {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),"lucky-flash-")),{publicKey,privateKey}=crypto.generateKeyPairSync("ed25519");
  const entries=[{role:"bootloader",file:"firmware/bootloader.bin",offset:"0x1000"},{role:"partitions",file:"firmware/partitions.bin",offset:"0x8000"},{role:"application",file:"firmware/firmware.bin",offset:"0x10000"}], tool={file:"tools/esptool.exe",version:"4.11.0"};
  for(const entry of [...entries,tool]){const file=path.join(root,entry.file);fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,entry.role||"esptool");entry.sha256=crypto.createHash("sha256").update(fs.readFileSync(file)).digest("hex");}
  const manifest={formatVersion:1,firmwareVersion:"1.4.0",buildId:"test",targetChip:"esp32",boardProfile:"esp32dev",flashSize:"4MB",flashMode:"dio",flashFrequency:"40m",releaseChannel:"test",esptool:tool,files:entries};manifest.signature=crypto.sign(null,canonicalManifest(manifest),privateKey).toString("base64");fs.writeFileSync(path.join(root,"manifest.json"),JSON.stringify(manifest));
  return {root,publicKey:publicKey.export({type:"spki",format:"pem"}),manifest};
}
function fakeSpawn(calls){return (tool,args)=>{calls.push({tool,args});const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();process.nextTick(()=>{const command=args.at(-1);let output="";if(command==="chip_id")output="Chip is ESP32\n";if(command==="flash_id")output="Detected flash size: 4MB\n";child.stdout.emit("data",Buffer.from(output));child.emit("close",0);});return child;};}
function service(pkg,calls=[],extra={}){let n=0;return new UsbFlasherService({packageService:pkg,portProvider:{list:()=>[]},relaySafe:async()=>true,spawnProcess:fakeSpawn(calls),randomBytes:size=>Buffer.alloc(size,++n),...extra});}

test("signed manifest verifies every bundled file and rejects tampering",()=>{const fixture=signedPackage(),pkg=new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey});assert.equal(pkg.verify().manifest.firmwareVersion,"1.4.0");fs.appendFileSync(path.join(fixture.root,"firmware/firmware.bin"),"tamper");assert.throws(()=>pkg.verify(),error=>error.code==="PACKAGE_HASH_MISMATCH");});
test("manifest cannot escape the approved package root",()=>{const fixture=signedPackage();fixture.manifest.files[0].file="../outside.bin";fixture.manifest.signature="bad";fs.writeFileSync(path.join(fixture.root,"manifest.json"),JSON.stringify(fixture.manifest));assert.throws(()=>new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey}).verify());});
test("existing update writes application only and never erases NVS",async()=>{const fixture=signedPackage(),calls=[],flasher=service(new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey}),calls);const csrf=flasher.issueCsrf("owner"),token=flasher.issueToken("owner",csrf.csrfToken),started=await flasher.start({port:"COM7",mode:"update",operationToken:token.operationToken},"owner");await new Promise(resolve=>setTimeout(resolve,30));const write=calls.find(call=>call.args.includes("write_flash"));assert.ok(write);assert.ok(write.args.includes("0x10000"));assert.ok(!write.args.includes("0x9000"));assert.ok(!write.args.includes("erase_flash"));assert.equal(flasher.status(started.id).state,"COMPLETED");});
test("new install requires destructive confirmation and an approved NVS generator",async()=>{const fixture=signedPackage(),flasher=service(new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey}));let csrf=flasher.issueCsrf("owner"),token=flasher.issueToken("owner",csrf.csrfToken);await assert.rejects(()=>flasher.start({port:"COM3",mode:"new",relayCount:4,operationToken:token.operationToken},"owner"),error=>error.code==="DESTRUCTIVE_CONFIRMATION_REQUIRED");csrf=flasher.issueCsrf("owner");token=flasher.issueToken("owner",csrf.csrfToken);const started=await flasher.start({port:"COM3",mode:"new",relayCount:4,operationToken:token.operationToken,destructiveConfirmation:"ERASE NEW DEVICE"},"owner");await new Promise(resolve=>setTimeout(resolve,30));assert.equal(flasher.status(started.id).error,"NVS_GENERATOR_UNAVAILABLE");});
test("operation and CSRF tokens are single-purpose and fail closed",()=>{const fixture=signedPackage(),flasher=service(new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey}));assert.throws(()=>flasher.issueToken("owner","bad"),error=>error.code==="CSRF_INVALID");const csrf=flasher.issueCsrf("owner"),token=flasher.issueToken("owner",csrf.csrfToken);flasher.consumeToken(token.operationToken,"owner");assert.throws(()=>flasher.consumeToken(token.operationToken,"owner"),error=>error.code==="OPERATION_TOKEN_INVALID");});
test("multiple candidate ports are never auto-selected",()=>{const fixture=signedPackage(),flasher=service(new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey}),[],{portProvider:{list:()=>[{port:"COM4",vid:"10C4",pid:"EA60"},{port:"COM9",vid:"1A86",pid:"7523"}]}});assert.deepEqual(flasher.ports().map(item=>item.port),["COM4","COM9"]);});
test("failed operation can be dismissed but pending enrollment fails closed",()=>{const fixture=signedPackage(),flasher=service(new FirmwarePackageService({packageRoot:fixture.root,publicKey:fixture.publicKey}));flasher.active={id:"failed",actorId:"owner",state:"FAILED"};assert.deepEqual(flasher.dismiss("failed","owner"),{dismissed:true});assert.equal(flasher.active,null);flasher.active={id:"pending",actorId:"owner",state:"ENROLLMENT_PENDING",pendingEnrollment:{deviceKey:"secret"}};assert.throws(()=>flasher.dismiss("pending","owner"),error=>error.code==="FLASH_DISMISSAL_UNSAFE");assert.equal(flasher.active.pendingEnrollment.deviceKey,"secret");});
