const DEVICE_TYPES = Object.freeze({ RELAY_CONTROLLER: "RELAY_CONTROLLER" });
const DEVICE_STATUS = Object.freeze({ ONLINE: "ONLINE", OFFLINE: "OFFLINE", CHECKING: "CHECKING", STALE: "STALE", TIMEOUT: "TIMEOUT", UNKNOWN: "UNKNOWN", WARNING: "WARNING", ERROR: "ERROR" });
const SUPPORTED_RELAY_COUNTS = Object.freeze([2, 4, 8]);

module.exports = { DEVICE_TYPES, DEVICE_STATUS, SUPPORTED_RELAY_COUNTS };
