const ROLES = Object.freeze({ OWNER: "OWNER", MANAGER: "MANAGER", CASHIER: "CASHIER", STAFF: "STAFF" });
const PERMISSIONS = Object.freeze({ TABLE_OPEN: "table.open", TABLE_PAUSE: "table.pause", TABLE_RESUME: "table.resume", TABLE_CLOSE: "table.close", PAYMENT_CONFIRM: "payment.confirm", BILL_VIEW: "bill.view", BILL_VOID: "bill.void", REPORT_VIEW: "report.view", SETTINGS_MANAGE: "settings.manage", USER_MANAGE: "user.manage", PRODUCT_VIEW: "product.view", PRODUCT_MANAGE: "product.manage", INVENTORY_MANAGE: "inventory.manage" });
const ROLE_PERMISSIONS = Object.freeze({
  OWNER: Object.values(PERMISSIONS),
  MANAGER: [PERMISSIONS.TABLE_OPEN, PERMISSIONS.TABLE_PAUSE, PERMISSIONS.TABLE_RESUME, PERMISSIONS.TABLE_CLOSE, PERMISSIONS.PAYMENT_CONFIRM, PERMISSIONS.BILL_VIEW, PERMISSIONS.BILL_VOID, PERMISSIONS.REPORT_VIEW, PERMISSIONS.PRODUCT_VIEW, PERMISSIONS.PRODUCT_MANAGE, PERMISSIONS.INVENTORY_MANAGE],
  CASHIER: [PERMISSIONS.TABLE_OPEN, PERMISSIONS.TABLE_CLOSE, PERMISSIONS.PAYMENT_CONFIRM, PERMISSIONS.BILL_VIEW, PERMISSIONS.PRODUCT_VIEW],
  STAFF: [PERMISSIONS.TABLE_OPEN, PERMISSIONS.TABLE_PAUSE, PERMISSIONS.TABLE_RESUME, PERMISSIONS.PRODUCT_VIEW]
});
function hasPermission(role, permission) { return (ROLE_PERMISSIONS[role] || []).includes(permission); }
module.exports = { ROLES, PERMISSIONS, ROLE_PERMISSIONS, hasPermission };
