#include "serial/SerialRecoveryService.h"
#include <ArduinoJson.h>
#include <mbedtls/md.h>
#include "utils/ApiJson.h"

namespace lucky {
namespace { constexpr const char* kRequestPrefix = "LUCKY_RECOVERY:"; constexpr const char* kResponsePrefix = "LUCKY_RECOVERY_RESPONSE:"; }
SerialRecoveryService::SerialRecoveryService(Stream& serial, ConfigService& config, RelayService& relays, WifiProvisioningService& wifi, SetupModeService& setup, ILogger& logger)
  : serial_(serial), config_(config), relays_(relays), wifi_(wifi), setup_(setup), logger_(logger) {}
bool SerialRecoveryService::relaySafe() const { for (const auto& item : relays_.getAllStates()) if (item.state == RelayState::On) return false; return true; }
bool SerialRecoveryService::validText(const String& value, std::size_t minimum, std::size_t maximum) const { return value.length() >= minimum && value.length() <= maximum; }
bool SerialRecoveryService::constantTimeEqual(const String& left, const String& right) { const std::size_t maximum=max(left.length(),right.length());std::size_t difference=left.length()^right.length();for(std::size_t i=0;i<maximum;++i)difference|=static_cast<uint8_t>((i<left.length()?left[i]:0)^(i<right.length()?right[i]:0));return difference==0; }
String SerialRecoveryService::hmac(const String& key, const String& message) { unsigned char output[32]{};const auto* info=mbedtls_md_info_from_type(MBEDTLS_MD_SHA256);mbedtls_md_hmac(info,reinterpret_cast<const unsigned char*>(key.c_str()),key.length(),reinterpret_cast<const unsigned char*>(message.c_str()),message.length(),output);char encoded[65]{};for(std::size_t i=0;i<32;++i)snprintf(encoded+i*2,3,"%02x",output[i]);return String(encoded); }
void SerialRecoveryService::response(const char* command, bool ok, const char* errorCode) { JsonDocument doc;doc["command"]=command;doc["ok"]=ok;doc["deviceId"]=config_.getConfig().deviceId;doc["relayCount"]=config_.getRelayCount();doc["firmwareVersion"]=defaults::kFirmwareVersion;doc["apiVersion"]=defaults::kApiVersion;if(errorCode)doc["error"]=errorCode;serial_.print(kResponsePrefix);serial_.println(serializeDocument(doc)); }
void SerialRecoveryService::handle(const String& payload) {
  JsonDocument doc;if(deserializeJson(doc,payload)){response("UNKNOWN",false,"INVALID_JSON");return;}const String command=doc["command"]|"";const String transitionId=doc["transitionId"]|"";
  if(command=="IDENTIFY"){response("IDENTIFY",true);return;}
  if(command=="GET_RELAY_SAFETY"){JsonDocument out;out["command"]=command;out["ok"]=true;out["deviceId"]=config_.getConfig().deviceId;out["relayCount"]=config_.getRelayCount();out["safe"]=relaySafe();JsonArray active=out["activeChannels"].to<JsonArray>();for(const auto& item:relays_.getAllStates())if(item.state==RelayState::On)active.add(item.channel);serial_.print(kResponsePrefix);serial_.println(serializeDocument(out));return;}
  if(!relaySafe()){response(command.c_str(),false,"RELAY_SAFE_STATE_CONFLICT");return;}
  const String requestNonce=doc["nonce"]|"",requestProof=doc["proof"]|"";
  const bool currentKeyAuthorized=validText(requestNonce,32,128)&&constantTimeEqual(requestProof,hmac(config_.getConfig().apiKey,command+"|"+requestNonce+"|"+transitionId));
  if(command=="STAGE_WIFI") { const String ssid=doc["ssid"]|"",password=doc["password"]|"";if(!currentKeyAuthorized||!validText(transitionId,16,128)||!validText(ssid,1,32)||password.length()>63){response(command.c_str(),false,"WIFI_STAGE_INVALID");return;}const bool done=wifi_.stage(ssid,password,transitionId);response(command.c_str(),done,done?nullptr:"WIFI_STAGE_REJECTED");return; }
  if(command=="GET_TRANSITION_STATUS"||command=="VERIFY_TRANSITION") { if(!currentKeyAuthorized){response(command.c_str(),false,"AUTHENTICATION_FAILED");return;}JsonDocument out;out["command"]=command;out["ok"]=true;out["deviceId"]=config_.getConfig().deviceId;out["relayCount"]=config_.getRelayCount();out["transitionId"]=wifi_.transitionId();out["state"]=wifi_.state();out["errorCode"]=wifi_.errorCode();out["proof"]=hmac(config_.getConfig().apiKey,requestNonce+"|"+config_.getConfig().deviceId+"|"+String(config_.getRelayCount())+"|"+transitionId);serial_.print(kResponsePrefix);serial_.println(serializeDocument(out));return; }
  if(command=="COMMIT_WIFI") { if(!currentKeyAuthorized){response(command.c_str(),false,"AUTHENTICATION_FAILED");return;}const bool done=wifi_.commit(transitionId);response(command.c_str(),done,done?nullptr:"WIFI_COMMIT_REJECTED");return; }
  if(command=="ROLLBACK_WIFI") { if(!currentKeyAuthorized){response(command.c_str(),false,"AUTHENTICATION_FAILED");return;}const bool done=wifi_.rollback(transitionId,"USB_RECOVERY_ROLLBACK");response(command.c_str(),done,done?nullptr:"WIFI_ROLLBACK_REJECTED");return; }
  if(command=="STAGE_DEVICE_KEY") { const String setupCode=doc["setupCode"]|"",newKey=doc["deviceKey"]|"";String error;if(!validText(transitionId,16,128)||!validText(newKey,43,128)||!setup_.authenticateSetupCodeForRecovery(setupCode,error)){response(command.c_str(),false,error.isEmpty()?"KEY_STAGE_INVALID":error.c_str());return;}if(!config_.stageDeviceKey(newKey,transitionId)){response(command.c_str(),false,"KEY_STAGE_FAILED");return;}keyTransitionId_=transitionId;keyTransitionStartedMs_=millis();response(command.c_str(),true);return; }
  if(command=="VERIFY_DEVICE_KEY") { const String nonce=doc["nonce"]|"";if(transitionId!=keyTransitionId_||!validText(nonce,32,128)){response(command.c_str(),false,"KEY_TRANSITION_INVALID");return;}JsonDocument out;out["command"]=command;out["ok"]=true;out["deviceId"]=config_.getConfig().deviceId;out["relayCount"]=config_.getRelayCount();out["proof"]=hmac(config_.candidateDeviceKey(),nonce+"|"+config_.getConfig().deviceId+"|"+String(config_.getRelayCount())+"|"+transitionId);serial_.print(kResponsePrefix);serial_.println(serializeDocument(out));return; }
  if(command=="COMMIT_DEVICE_KEY") { const String nonce=doc["nonce"]|"",proof=doc["proof"]|"";const String expected=hmac(config_.candidateDeviceKey(),"commit|"+nonce+"|"+transitionId);if(transitionId!=keyTransitionId_||!constantTimeEqual(proof,expected)||!config_.commitDeviceKey(transitionId)){response(command.c_str(),false,"KEY_COMMIT_REJECTED");return;}keyTransitionId_="";keyTransitionStartedMs_=0;response(command.c_str(),true);return; }
  if(command=="ROLLBACK_DEVICE_KEY") { const bool done=config_.rollbackDeviceKey(transitionId);keyTransitionId_="";keyTransitionStartedMs_=0;response(command.c_str(),done,done?nullptr:"KEY_ROLLBACK_REJECTED");return; }
  response(command.c_str(),false,"UNKNOWN_COMMAND");
}
void SerialRecoveryService::loop() { if(!keyTransitionId_.isEmpty()&&millis()-keyTransitionStartedMs_>=kTransactionTimeoutMs){config_.rollbackDeviceKey(keyTransitionId_);keyTransitionId_="";keyTransitionStartedMs_=0;logger_.warning("USB_KEY_ROTATION_ROLLED_BACK","USB key rotation timed out");}while(serial_.available()){const char c=static_cast<char>(serial_.read());if(c=='\n'){if(input_.startsWith(kRequestPrefix))handle(input_.substring(strlen(kRequestPrefix)));input_="";}else if(c!='\r'){if(input_.length()<kMaximumPayload+strlen(kRequestPrefix))input_+=c;else input_="";}} }
}
