const crypto = require("crypto");
const { ROLES } = require("../domain/permissions");
const PASSWORD_POLICY = "Password must be at least 10 characters and contain uppercase, lowercase, number, and special character";
const assertPasswordPolicy = password => { const value=String(password||""); if(value.length<10||!/[A-Z]/.test(value)||!/[a-z]/.test(value)||!/[0-9]/.test(value)||!/[^A-Za-z0-9]/.test(value)) throw new Error(PASSWORD_POLICY); return value; };
const hashPassword = password => { const salt = crypto.randomBytes(16).toString("hex"); const hash = crypto.scryptSync(assertPasswordPolicy(password), salt, 64).toString("hex"); return `scrypt$${salt}$${hash}`; };
const verifyPassword = (password, stored) => { const [algorithm, salt, expected] = String(stored || "").split("$"); if (algorithm !== "scrypt" || !salt || !expected) return false; const actual = crypto.scryptSync(String(password), salt, 64); return crypto.timingSafeEqual(actual, Buffer.from(expected, "hex")); };
class AuthService {
  constructor(repository, clock = () => new Date(), audit = () => {}) { this.repository = repository; this.clock = clock; this.audit = audit; this.sessions = new Map(); }
  now(){ return this.clock().toISOString(); }
  bootstrap() { if (this.repository.users().length) return null; const password = process.env.LUCKY_BOOTSTRAP_PASSWORD || "ChangeMe123!"; return this.repository.add({ userId: "admin", username: "admin", passwordHash: hashPassword(password), displayName: "Owner", role: ROLES.OWNER, status: "ACTIVE", createdAt: this.now(), updatedAt: this.now(), passwordChangedAt:null, lastLoginAt:null, failedLoginCount:0, lockedUntil:null, mustChangePassword: true }); }
  login(username, password) { const user = this.repository.findByUsername(username); const now=Date.now(); if(!user || !verifyPassword(password, user.passwordHash)){ if(user){ user.failedLoginCount=(user.failedLoginCount||0)+1; if(user.failedLoginCount>=5){user.lockedUntil=new Date(now+15*60*1000).toISOString(); this.audit("ACCOUNT_LOCKED", "SYSTEM", user.userId); } this.repository.saveUser(user); this.audit("LOGIN_FAILED", "UNKNOWN", user.userId); } throw new Error("Invalid username or password"); } if(user.lockedUntil && new Date(user.lockedUntil).getTime()>now) throw new Error("Account is temporarily locked"); if(user.status!=="ACTIVE") throw new Error("User is disabled"); Object.assign(user,{failedLoginCount:0,lockedUntil:null,lastLoginAt:this.now(),updatedAt:this.now()}); this.repository.saveUser(user); const token=crypto.randomBytes(32).toString("hex"); this.sessions.set(token,{userId:user.userId,expiresAt:now+8*60*60*1000,lastActivityAt:now}); this.audit("LOGIN_SUCCESS",user.userId,user.userId); return {token,user:this.publicUser(user)}; }
  logout(token, actorId="SYSTEM") { const current=this.current(token); if(token) this.sessions.delete(token); if(current) this.audit("LOGOUT",actorId,current.userId); }
  current(token) { const session = this.sessions.get(token), now=Date.now(); if (!session || session.expiresAt < now || now-session.lastActivityAt>8*60*60*1000) { if(token) this.sessions.delete(token); return null; } session.lastActivityAt=now; const user=this.repository.findById(session.userId); return user?.status==="ACTIVE"?this.publicUser(user):null; }
  createUser({username,displayName,role,password},actorId){ const normalized=String(username||"").trim().toLowerCase(); if(!/^[a-z0-9_.-]{3,30}$/.test(normalized)) throw new Error("Invalid username"); if(this.repository.findByUsername(normalized)) throw new Error("Username already exists"); if(!Object.values(ROLES).includes(role)) throw new Error("Invalid role"); const user={userId:crypto.randomUUID(),username:normalized,passwordHash:hashPassword(password),displayName:String(displayName||normalized).trim(),role,status:"ACTIVE",createdAt:this.now(),updatedAt:this.now(),passwordChangedAt:null,lastLoginAt:null,failedLoginCount:0,lockedUntil:null,mustChangePassword:true}; this.repository.add(user); this.audit("USER_CREATED",actorId,user.userId); return this.publicUser(user); }
  updateUser(id,changes,actorId){ const user=this.repository.findById(id); if(!user) throw new Error("User not found"); if(changes.displayName) user.displayName=String(changes.displayName).trim(); if(changes.role){ if(!Object.values(ROLES).includes(changes.role)) throw new Error("Invalid role"); user.role=changes.role; this.audit("ROLE_CHANGED",actorId,id,{role:user.role}); } user.updatedAt=this.now(); this.repository.saveUser(user); return this.publicUser(user); }
  setStatus(id,status,actorId){ const user=this.repository.findById(id); if(!user) throw new Error("User not found"); if(!["ACTIVE","DISABLED"].includes(status)) throw new Error("Invalid status"); user.status=status; user.updatedAt=this.now(); if(status==="ACTIVE"){user.lockedUntil=null;user.failedLoginCount=0;this.audit("ACCOUNT_UNLOCKED",actorId,id);} this.repository.saveUser(user); this.audit(status==="ACTIVE"?"USER_ENABLED":"USER_DISABLED",actorId,id); return this.publicUser(user); }
  changePassword(id,password,actorId,reset=false){ const user=this.repository.findById(id); if(!user) throw new Error("User not found"); user.passwordHash=hashPassword(password); user.passwordChangedAt=this.now(); user.updatedAt=this.now(); user.mustChangePassword=!!reset; user.failedLoginCount=0; user.lockedUntil=null; this.repository.saveUser(user); this.audit(reset?"PASSWORD_RESET":"PASSWORD_CHANGED",actorId,id); return this.publicUser(user); }
  publicUser(user) { const { passwordHash, ...safe } = user; return safe; }
}
module.exports = { AuthService, hashPassword, verifyPassword, assertPasswordPolicy, PASSWORD_POLICY };
