const crypto = require("crypto");
const { ROLES } = require("../domain/permissions");
const PASSWORD_POLICY = "รหัสผ่านต้องมีความยาวอย่างน้อย 8 ตัว";
const assertPasswordPolicy = password => { const value=String(password||""); if(Array.from(value).length<8) throw new Error(PASSWORD_POLICY); return value; };
const hashPassword = password => { const salt = crypto.randomBytes(16).toString("hex"); const hash = crypto.scryptSync(assertPasswordPolicy(password), salt, 64).toString("hex"); return `scrypt$${salt}$${hash}`; };
const verifyPassword = (password, stored) => { const [algorithm, salt, expected] = String(stored || "").split("$"); if (algorithm !== "scrypt" || !salt || !expected) return false; const actual = crypto.scryptSync(String(password), salt, 64); return crypto.timingSafeEqual(actual, Buffer.from(expected, "hex")); };
class AuthService {
  constructor(repository, clock = () => new Date(), audit = () => {}, security = () => ({ timeoutMinutes:480, warningMinutes:5, maxLoginAttempts:5, lockDurationMinutes:15 })) { this.repository = repository; this.clock = clock; this.audit = audit; this.security = security; this.sessions = new Map(); }
  now(){ return this.clock().toISOString(); }
  bootstrap() { if (this.repository.users().length) return null; const password = process.env.LUCKY_BOOTSTRAP_PASSWORD || "123456789"; return this.repository.add({ userId: "admin", username: "admin", passwordHash: hashPassword(password), displayName: "Owner", role: ROLES.OWNER, status: "ACTIVE", createdAt: this.now(), updatedAt: this.now(), passwordChangedAt:null, lastLoginAt:null, failedLoginCount:0, lockedUntil:null, mustChangePassword: true }); }
  login(username, password) { const user = this.repository.findByUsername(username); const now=Date.now(), policy=this.security(); if(!user || !verifyPassword(password, user.passwordHash)){ if(user){ user.failedLoginCount=(user.failedLoginCount||0)+1; if(user.failedLoginCount>=policy.maxLoginAttempts){user.lockedUntil=new Date(now+policy.lockDurationMinutes*60*1000).toISOString(); this.audit("ACCOUNT_LOCKED", "SYSTEM", user.userId); } this.repository.saveUser(user); this.audit("LOGIN_FAILED", "UNKNOWN", user.userId); } throw new Error("Invalid username or password"); } if(user.lockedUntil && new Date(user.lockedUntil).getTime()>now) throw new Error("Account is temporarily locked"); if(user.status!=="ACTIVE") throw new Error("User is disabled"); Object.assign(user,{failedLoginCount:0,lockedUntil:null,lastLoginAt:this.now(),updatedAt:this.now()}); this.repository.saveUser(user); const token=crypto.randomBytes(32).toString("hex"); this.sessions.set(token,{id:crypto.randomUUID(),userId:user.userId,createdAt:now,lastActivityAt:now}); this.audit("SESSION_CREATED",user.userId,user.userId); this.audit("LOGIN_SUCCESS",user.userId,user.userId); return {token,user:this.publicUser(user)}; }
  logout(token, actorId="SYSTEM") { const current=this.current(token); if(token) this.sessions.delete(token); if(current) this.audit("LOGOUT",actorId,current.userId); }
  current(token) { const session = this.sessions.get(token), now=Date.now(), timeout=this.security().timeoutMinutes*60*1000; if (!session || now-session.lastActivityAt>timeout) { if(token){const old=this.sessions.get(token);this.sessions.delete(token);if(old)this.audit("SESSION_EXPIRED",old.userId,old.userId,{sessionId:old.id});} return null; } session.lastActivityAt=now; const user=this.repository.findById(session.userId); return user?.status==="ACTIVE"?this.publicUser(user):null; }
  sessionStatus(token){ const session=this.sessions.get(token); if(!session||!this.current(token)) return null; const policy=this.security(), remaining=Math.max(0,policy.timeoutMinutes*60*1000-(Date.now()-session.lastActivityAt)); return {sessionId:session.id,remainingMs:remaining,warningMs:policy.warningMinutes*60*1000}; }
  refreshSession(token,actorId){ const session=this.sessions.get(token); if(!session||!this.current(token)) throw new Error("Session expired"); session.lastActivityAt=Date.now(); this.audit("SESSION_RENEWED",actorId,session.userId,{sessionId:session.id}); return this.sessionStatus(token); }
  listSessions(){ return [...this.sessions.entries()].map(([token,s])=>({id:s.id,userId:s.userId,loginTime:new Date(s.createdAt).toISOString(),lastActivity:new Date(s.lastActivityAt).toISOString(),browser:null,ipAddress:null,token})); }
  revokeSession(id,actorId,currentToken){ for(const [token,session] of this.sessions){if(session.id===id&&token!==currentToken){this.sessions.delete(token);this.audit("SESSION_FORCE_LOGOUT",actorId,session.userId,{sessionId:id});return true;}} return false; }
  createUser({username,displayName,role,password},actorId){ const normalized=String(username||"").trim().toLowerCase(); if(!/^[a-z0-9_.-]{3,30}$/.test(normalized)) throw new Error("Invalid username"); if(this.repository.findByUsername(normalized)) throw new Error("Username already exists"); if(!Object.values(ROLES).includes(role)) throw new Error("Invalid role"); const user={userId:crypto.randomUUID(),username:normalized,passwordHash:hashPassword(password),displayName:String(displayName||normalized).trim(),role,status:"ACTIVE",createdAt:this.now(),updatedAt:this.now(),passwordChangedAt:null,lastLoginAt:null,failedLoginCount:0,lockedUntil:null,mustChangePassword:true}; this.repository.add(user); this.audit("USER_CREATED",actorId,user.userId); return this.publicUser(user); }
  updateUser(id,changes,actorId){ const user=this.repository.findById(id); if(!user) throw new Error("User not found"); if(changes.username!==undefined){const username=String(changes.username).trim().toLowerCase();if(!/^[a-z0-9_.-]{3,30}$/.test(username)||this.repository.findByUsername(username)?.userId!==id)throw new Error("Invalid or duplicate username");user.username=username;} if(changes.displayName!==undefined&&!String(changes.displayName).trim())throw new Error("Display name is required"); if(changes.displayName) user.displayName=String(changes.displayName).trim(); if(changes.role){ if(!Object.values(ROLES).includes(changes.role)) throw new Error("Invalid role"); user.role=changes.role; this.audit("ROLE_CHANGED",actorId,id,{role:user.role}); } user.updatedAt=this.now(); this.repository.saveUser(user); return this.publicUser(user); }
  setStatus(id,status,actorId){ const user=this.repository.findById(id); if(!user) throw new Error("User not found"); if(!["ACTIVE","DISABLED"].includes(status)) throw new Error("Invalid status"); user.status=status; user.updatedAt=this.now(); if(status==="ACTIVE"){user.lockedUntil=null;user.failedLoginCount=0;this.audit("ACCOUNT_UNLOCKED",actorId,id);} this.repository.saveUser(user); this.audit(status==="ACTIVE"?"USER_ENABLED":"USER_DISABLED",actorId,id); return this.publicUser(user); }
  changePassword(id,password,actorId,reset=false){ const user=this.repository.findById(id); if(!user) throw new Error("User not found"); user.passwordHash=hashPassword(password); user.passwordChangedAt=this.now(); user.updatedAt=this.now(); user.mustChangePassword=!!reset; user.failedLoginCount=0; user.lockedUntil=null; this.repository.saveUser(user); this.audit(reset?"PASSWORD_RESET":"PASSWORD_CHANGED",actorId,id); return this.publicUser(user); }
  publicUser(user) { const { passwordHash, ...safe } = user; return safe; }
}
module.exports = { AuthService, hashPassword, verifyPassword, assertPasswordPolicy, PASSWORD_POLICY };
