const crypto=require("crypto");
const TIERS=new Set(["STANDARD","SILVER","GOLD","PLATINUM"]);
const clean=v=>String(v??"").trim();
class MemberService{
 constructor(repository,{clock=()=>new Date(),audit=()=>{}}={}){this.repository=repository;this.clock=clock;this.audit=audit;}
 now(){return this.clock().toISOString();}
 normalize(){let changed=false;for(const m of this.repository.members()){if(!m.memberCode){m.memberCode=m.code||`M${String(this.repository.members().indexOf(m)+1).padStart(4,"0")}`;changed=true;}if(!m.displayName){m.displayName=m.name||[m.firstName,m.lastName].filter(Boolean).join(" ");changed=true;}for(const [k,v] of Object.entries({firstName:"",lastName:"",phone:"",email:"",birthday:"",gender:"",lineId:"",address:"",status:"ACTIVE",tier:"STANDARD",points:0,totalSpent:0,visitCount:0,lastVisitAt:null,createdBy:"SYSTEM",updatedBy:"SYSTEM"}))if(m[k]===undefined){m[k]=v;changed=true;}}if(changed)this.repository.save();}
 assertUnique(input,id){const code=clean(input.memberCode),phone=clean(input.phone),email=clean(input.email).toLowerCase();if(!code)throw new Error("Member code is required");if(this.repository.members().some(m=>m.id!==id&&(m.memberCode||m.code)===code))throw new Error("Member code already exists");if(phone&&this.repository.members().some(m=>m.id!==id&&clean(m.phone)===phone))throw new Error("Phone already exists");if(email&&this.repository.members().some(m=>m.id!==id&&clean(m.email).toLowerCase()===email))throw new Error("Email already exists");}
 create(input,actor){this.normalize();const now=this.now(),firstName=clean(input.firstName||input.name),lastName=clean(input.lastName),displayName=clean(input.displayName)||[firstName,lastName].filter(Boolean).join(" ");if(!displayName)throw new Error("Member name is required");const memberCode=clean(input.memberCode)||`M${String(this.repository.members().length+1).padStart(4,"0")}`;this.assertUnique({...input,memberCode},null);const m={id:crypto.randomUUID(),memberCode,code:memberCode,firstName,lastName,displayName,name:displayName,phone:clean(input.phone),email:clean(input.email),birthday:clean(input.birthday),gender:clean(input.gender),lineId:clean(input.lineId),address:clean(input.address),status:"ACTIVE",tier:TIERS.has(input.tier)?input.tier:"STANDARD",points:0,totalSpent:0,visitCount:0,lastVisitAt:null,createdAt:now,updatedAt:now,createdBy:actor,updatedBy:actor};this.repository.saveMember(m);this.audit("MEMBER_CREATED",actor,{memberId:m.id});return m;}
 update(id,input,actor){this.normalize();const m=this.repository.findById(id);if(!m)throw new Error("Member not found");const next={...m,...Object.fromEntries(Object.entries(input).filter(([k])=>["memberCode","firstName","lastName","displayName","phone","email","birthday","gender","lineId","address","tier"].includes(k)))};if(!TIERS.has(next.tier))throw new Error("Invalid tier");next.displayName=clean(next.displayName)||[next.firstName,next.lastName].filter(Boolean).join(" ");next.name=next.displayName;next.code=next.memberCode;this.assertUnique(next,id);Object.assign(m,next,{updatedAt:this.now(),updatedBy:actor});this.repository.saveMember(m);this.audit("MEMBER_UPDATED",actor,{memberId:id});return m;}
 list(q={}){this.normalize();const text=clean(q.search||q.q).toLowerCase(),status=clean(q.status);return this.repository.members().filter(m=>(!status||m.status===status)&&(!text||[m.memberCode,m.displayName,m.phone,m.email].some(v=>clean(v).toLowerCase().includes(text))));}
 status(id,status,actor){const m=this.repository.findById(id);if(!m)throw new Error("Member not found");if(!["ACTIVE","DISABLED"].includes(status))throw new Error("Invalid member status");m.status=status;m.updatedAt=this.now();m.updatedBy=actor;this.repository.saveMember(m);this.audit(status==="ACTIVE"?"MEMBER_ENABLED":"MEMBER_DISABLED",actor,{memberId:id});return m;}
 earned(total){return Math.floor(Number(total||0)/20);}
 earn(bill,actor){if(!bill.memberId||bill.pointsEarnedApplied)return null;const m=this.repository.findById(bill.memberId);if(!m||m.status!=="ACTIVE")return null;const points=this.earned(bill.total);const before=m.points;m.points+=points;m.totalSpent+=Number(bill.total||0);m.visitCount+=1;m.lastVisitAt=this.now();m.updatedAt=this.now();m.updatedBy=actor;bill.pointsEarned=points;bill.pointsBalance=m.points;bill.pointsEarnedApplied=true;this.repository.saveMember(m);this.repository.addPoint({id:crypto.randomUUID(),memberId:m.id,billId:bill.id,type:"EARN",points,balanceBefore:before,balanceAfter:m.points,createdAt:this.now(),createdBy:actor});this.audit("POINT_EARNED",actor,{memberId:m.id,billId:bill.id,points});return m;}
 void(bill,actor){if(!bill.memberId||!bill.pointsEarnedApplied||bill.pointsVoided)return null;const m=this.repository.findById(bill.memberId);if(!m)return null;const p=Number(bill.pointsEarned||0),before=m.points;m.points=Math.max(0,m.points-p);m.totalSpent=Math.max(0,m.totalSpent-Number(bill.total||0));m.updatedAt=this.now();m.updatedBy=actor;bill.pointsVoided=true;this.repository.saveMember(m);this.repository.addPoint({id:crypto.randomUUID(),memberId:m.id,billId:bill.id,type:"VOID",points:-p,balanceBefore:before,balanceAfter:m.points,createdAt:this.now(),createdBy:actor});this.audit("POINT_VOID",actor,{memberId:m.id,billId:bill.id,points:-p});return m;}
 history(id){return this.repository.points().filter(t=>t.memberId===id);}
}
module.exports={MemberService};
