const crypto = require("crypto");

const STATUSES = Object.freeze(["BOOKED", "DUE", "AWAITING_DECISION", "DEFERRED", "WAITING_TABLE", "OPENED_WAITING_CHECK_IN", "CHECKED_IN", "COMPLETED", "NO_SHOW", "CANCELLED"]);
const OPEN_STATUSES = new Set(["BOOKED", "DUE", "AWAITING_DECISION", "DEFERRED", "WAITING_TABLE"]);
const text = value => String(value || "").trim();
const bangkokDay = date => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Bangkok", year: "numeric", month: "2-digit", day: "2-digit" }).format(date);

class ReservationService {
  constructor(repository, depositService, { settings, tables, relay = async () => {}, startSession = async () => null, cancelSession = async () => {}, clock = () => new Date(), audit = () => {}, memberById = () => null } = {}) { Object.assign(this, { repository, depositService, settings, tables, relay, startSession, cancelSession, clock, audit, memberById }); this.decisionLocks=new Set(); }
  now() { return this.clock(); }
  stamp() { return this.now().toISOString(); }
  fail(code, message) { const error = new Error(message); error.code = code; throw error; }
  list(query = {}) { return this.repository.list().filter(item => (!query.status || item.status === query.status) && (!query.date || item.reservationDate === query.date) && (!query.phone || item.phone.includes(query.phone))).sort((a,b) => new Date(a.effectiveReservationAt || a.reservedAt) - new Date(b.effectiveReservationAt || b.reservedAt)); }
  get(id) { const item = this.repository.findById(id); if (!item) this.fail("RESERVATION_NOT_FOUND", "Reservation not found"); return item; }
  normalizeLegacy() { for (const item of this.repository.list()) { if (item.status !== "READY" && !(item.status === "WAITING_TABLE" && !item.decisionSelectedAt)) continue; item.status = item.status === "READY" && item.tableSessionId ? "OPENED_WAITING_CHECK_IN" : "AWAITING_DECISION"; if (item.status === "AWAITING_DECISION") { item.assignedTableId = null; item.checkInDeadlineAt = null; } this.timeline(item, "RESERVATION_LEGACY_STATUS_NORMALIZED", "SYSTEM"); this.save(item, "SYSTEM"); } }
  sequence(prefix, date, field) { return `${prefix}-${date.replaceAll("-", "")}-${String(this.repository.list().filter(x => x[field]?.startsWith(`${prefix}-${date.replaceAll("-", "")}-`)).length + 1).padStart(4, "0")}`; }
  timeline(item, event, actorId, details = {}) { item.timeline = [...(item.timeline || []), { event, occurredAt: this.stamp(), actorId, ...details }]; }
  save(item, actorId = "SYSTEM") { item.updatedAt = this.stamp(); item.updatedBy = actorId; item.version = Number(item.version || 1) + 1; return this.repository.update(item); }
  validate(input, config) { const customerName=text(input.customerName), phone=text(input.phone), reservationDate=text(input.reservationDate), reservationTime=text(input.reservationTime), paymentMethod=text(input.paymentMethod); if(!customerName)this.fail("VALIDATION_ERROR","Customer name is required"); if(!phone)this.fail("VALIDATION_ERROR","Phone number is required"); if(!reservationDate||!reservationTime||Number.isNaN(new Date(`${reservationDate}T${reservationTime}:00+07:00`).getTime()))this.fail("VALIDATION_ERROR","Valid reservation date and time are required"); const amountSatang=Number(input.amountSatang); if(config.depositRequired&&(!Number.isInteger(amountSatang)||amountSatang<=0))this.fail("VALIDATION_ERROR","Deposit is required"); if(config.depositRequired&&amountSatang<config.minimumDepositAmount*100)this.fail("VALIDATION_ERROR",`Deposit must be at least ${config.minimumDepositAmount} baht`); if(!paymentMethod)this.fail("VALIDATION_ERROR","Payment method is required"); if(input.paymentConfirmed!==true)this.fail("VALIDATION_ERROR","Deposit payment must be confirmed"); return {customerName,phone,reservationDate,reservationTime,paymentMethod,amountSatang}; }
  create(input,user) { if(!["OWNER","MANAGER","CASHIER"].includes(user.role))this.fail("FORBIDDEN","You cannot create reservations"); const config=this.settings().reservation, now=this.stamp(), memberId=text(input.memberId)||null, member=memberId?this.memberById(memberId):null; if(memberId&&(!member||member.status!=="ACTIVE"))this.fail("MEMBER_NOT_ACTIVE","Selected member is not active");
    // Booking for a member fills the name and phone from the member record, so the client does not
    // have to send back what the server already knows. Resolved BEFORE validation, not after, or a
    // member booking would be rejected for fields the member record could have supplied.
    // A member with no phone on file is the one case the record cannot cover: the booking is still
    // refused without one, since a phone reservation with no number to call back is useless. That
    // rule lives here and not only in the dialog, which is a usability aid.
    const value=this.validate({...input, customerName:text(input.customerName)||text(member?.displayName)||text(member?.name), phone:text(input.phone)||text(member?.phone)},config); const reservedAt=new Date(`${value.reservationDate}T${value.reservationTime}:00+07:00`).toISOString(), reservation={id:`RES-${crypto.randomUUID().slice(0,8)}`,reservationNumber:this.sequence("RSV",value.reservationDate,"reservationNumber"),depositReceiptNumber:this.sequence("DR",value.reservationDate,"depositReceiptNumber"),customerName:value.customerName,phone:value.phone,memberId,memberCode:member?.memberCode||null,memberName:member?.displayName||null,reservationDate:value.reservationDate,reservationTime:value.reservationTime,reservedAt,effectiveReservationAt:reservedAt,remark:text(input.remark),status:"BOOKED",assignedTableId:null,tableSessionId:null,openedAt:null,checkInDeadlineAt:null,checkedInAt:null,deferCount:0,lastAlertAt:null,alertAcknowledgedAt:null,cancelledAt:null,noShowAt:null,createdAt:now,createdBy:user.userId,updatedAt:now,updatedBy:user.userId,version:1,timeline:[{event:"RESERVATION_CREATED",occurredAt:now,actorId:user.userId}]}; const deposit=this.depositService.create({reservationId:reservation.id,receiptNumber:reservation.depositReceiptNumber,amountSatang:value.amountSatang,paymentMethod:value.paymentMethod,paymentReference:input.paymentReference},user.userId); this.repository.create(reservation); this.audit(memberId?"RESERVATION_MEMBER_LINKED":"RESERVATION_CREATED",user.userId,{entityType:"RESERVATION",entityId:reservation.id,depositId:deposit.id}); return {reservation,deposit}; }
  update(id, changes, user) { if(!["OWNER","MANAGER","CASHIER"].includes(user.role))this.fail("FORBIDDEN","You cannot edit reservations");const item=this.get(id);if(!OPEN_STATUSES.has(item.status))this.fail("VALIDATION_ERROR","Reservation can no longer be edited");["customerName","phone","remark"].forEach(key=>{if(changes[key]!==undefined)item[key]=text(changes[key]);});if(!item.customerName||!item.phone)this.fail("VALIDATION_ERROR","Customer name and phone number are required");this.timeline(item,"RESERVATION_UPDATED",user.userId);return this.save(item,user.userId); }
  async cancel(id,user) { if(!["OWNER","MANAGER","CASHIER"].includes(user.role))this.fail("FORBIDDEN","You cannot cancel reservations");const item=this.get(id);if(!OPEN_STATUSES.has(item.status))this.fail("VALIDATION_ERROR","Reservation cannot be cancelled");item.status="CANCELLED";item.cancelledAt=this.stamp();this.timeline(item,"CANCELLED",user.userId);this.save(item,user.userId);this.audit("CANCELLED",user.userId,{reservationId:item.id});return item; }
  availableTable(reservationId) { const reserved=new Set(this.repository.list().filter(x=>x.id!==reservationId&&x.status==="OPENED_WAITING_CHECK_IN"&&x.assignedTableId!=null).map(x=>String(x.assignedTableId))); return this.tables().find(table=>table.status==="free"&&!reserved.has(String(table.id)))||null; }
  priorityQueue() { return this.list().filter(item=>["WAITING_TABLE","AWAITING_DECISION","DUE","DEFERRED","BOOKED"].includes(item.status)).sort((a,b)=>{const ap=a.deferCount>0?0:1,bp=b.deferCount>0?0:1;return ap-bp||new Date(a.effectiveReservationAt||a.reservedAt)-new Date(b.effectiveReservationAt||b.reservedAt);}); }
  async processDue() { const now=this.now(), changed=[]; for(const item of this.repository.list()) { if(item.status==="OPENED_WAITING_CHECK_IN"&&new Date(item.checkInDeadlineAt)<=now){await this.noShow(item.id,{userId:"SYSTEM",role:"OWNER"},true);changed.push(item.id);continue;} if(["BOOKED","DEFERRED"].includes(item.status)&&new Date(item.effectiveReservationAt||item.reservedAt)<=now){item.status="AWAITING_DECISION";this.timeline(item,item.deferCount?"RESERVATION_DEFERRED_DUE":"RESERVATION_DUE","SYSTEM");this.save(item,"SYSTEM");this.audit("RESERVATION_DUE","SYSTEM",{reservationId:item.id});changed.push(item.id);} } return changed; }
  // Two waiting states hold a customer who is (usually) standing at the counter, and neither used to
  // be told when a table came free:
  //   DEFERRED      — staff postponed the decision; the prompt only came back when the clock ran out,
  //                   so a table freeing up two minutes later went unnoticed for the rest of the wait.
  //   WAITING_TABLE — staff already chose "open now" and nothing was free. That decision is made;
  //                   this one is pure waiting, and arguably the more urgent of the two.
  // Both now re-alert while a table is actually available, on their own slower cadence
  // (tableFreeAlertMinutes) so a table that opens and closes repeatedly does not machine-gun the
  // counter. Time-due alerts keep the faster alertRepeatMinutes they always had.
  TABLE_FREE_WAITING_STATUSES = ["DEFERRED", "WAITING_TABLE"];
  pendingAlerts() {
    const config=this.settings().reservation; if(!config.alertEnabled)return []; const now=this.now();
    const due=item=>item.status==="AWAITING_DECISION"&&(!item.lastAlertAt||now-new Date(item.lastAlertAt)>=config.alertRepeatMinutes*60000);
    const freed=item=>this.TABLE_FREE_WAITING_STATUSES.includes(item.status)&&Boolean(this.availableTable(item.id))&&(!item.lastAlertAt||now-new Date(item.lastAlertAt)>=Math.max(1,Number(config.tableFreeAlertMinutes||5))*60000);
    return this.priorityQueue().filter(item=>due(item)||freed(item)).map(item=>{
      const reason=due(item)?"DUE":"TABLE_FREE";
      item.lastAlertAt=this.stamp();
      this.timeline(item,reason==="TABLE_FREE"?"RESERVATION_TABLE_FREE_ALERTED":"RESERVATION_ALERTED","SYSTEM");
      this.save(item,"SYSTEM");
      this.audit(reason==="TABLE_FREE"?"RESERVATION_TABLE_FREE_ALERTED":"RESERVATION_ALERTED","SYSTEM",{reservationId:item.id});
      return { ...this.alertItem(item), reason };
    });
  }
  // Everything currently waiting that could be seated right now. Drives the banner above the table
  // cards — the non-interrupting half of the same signal the popup carries.
  waitingWithTable() {
    return this.priorityQueue()
      .filter(item=>["AWAITING_DECISION",...this.TABLE_FREE_WAITING_STATUSES].includes(item.status))
      .map(item=>({ ...this.alertItem(item), status: item.status }))
      .filter(item=>item.tableAvailable);
  }
  alertItem(item) { const deposit=this.depositService.list({reservationId:item.id})[0]||null, table=this.availableTable(item.id); return {reservationId:item.id,reservationNumber:item.reservationNumber,version:item.version,customerName:item.customerName,memberCode:item.memberCode,phone:item.phone,originalReservationAt:item.reservedAt,effectiveReservationAt:item.effectiveReservationAt||item.reservedAt,deferCount:item.deferCount||0,remark:item.remark,depositAmountSatang:deposit?.amountSatang||0,tableAvailable:Boolean(table),availableTableName:table?.name||null}; }
  assertVersion(item, expected) { if(expected!==undefined&&expected!==null&&Number(expected)!==Number(item.version||1))this.fail("VERSION_CONFLICT","Reservation has been changed by another user"); }
  acquireDecision(id) { if(this.decisionLocks.has(id))this.fail("RESERVATION_OPERATION_IN_PROGRESS","Another reservation decision is in progress");this.decisionLocks.add(id); }
  async openNow(id,user,expectedVersion) {
    if(!["OWNER","MANAGER","CASHIER"].includes(user.role))this.fail("FORBIDDEN","You cannot open a reservation");
    this.acquireDecision(id);
    try {
      const item=this.get(id);this.assertVersion(item,expectedVersion);
      // Openable from any waiting state, not just AWAITING_DECISION: the table-free alert and the
      // banner above the table cards both fire while the reservation sits in DEFERRED or
      // WAITING_TABLE, and their whole point is a working "open now" button.
      if(!["AWAITING_DECISION",...this.TABLE_FREE_WAITING_STATUSES].includes(item.status))this.fail(item.status==="OPENED_WAITING_CHECK_IN"?"RESERVATION_ALREADY_OPENED":"RESERVATION_NOT_AWAITING_DECISION","Reservation is not awaiting a decision");
      item.decisionSelectedAt=this.stamp();item.decisionSelectedBy=user.userId;this.timeline(item,"RESERVATION_OPEN_NOW_SELECTED",user.userId);
      const table=this.availableTable(item.id);
      if(!table){item.status="WAITING_TABLE";this.timeline(item,"RESERVATION_WAITING_TABLE",user.userId);this.save(item,user.userId);this.audit("RESERVATION_WAITING_TABLE",user.userId,{reservationId:item.id});return {reservation:item,table:null,session:null};}
      item.assignedTableId=table.id;await this.relay(table,"on");const session=await this.startSession(item,user);item.tableSessionId=session?.id||null;item.status="OPENED_WAITING_CHECK_IN";item.openedAt=this.stamp();item.checkInDeadlineAt=new Date(this.now().getTime()+this.settings().reservation.checkInGraceMinutes*60000).toISOString();this.timeline(item,"TABLE_ASSIGNED",user.userId,{tableId:table.id});this.timeline(item,"SESSION_STARTED",user.userId,{tableSessionId:item.tableSessionId});this.timeline(item,"WAITING_FOR_CHECK_IN",user.userId);this.save(item,user.userId);this.audit("RESERVATION_TABLE_OPENED",user.userId,{reservationId:item.id,tableId:table.id,tableSessionId:item.tableSessionId});return {reservation:item,table,session};
    } finally { this.decisionLocks.delete(id); }
  }
  defer(id,user,expectedVersion) { if(!["OWNER","MANAGER","CASHIER"].includes(user.role))this.fail("FORBIDDEN","You cannot defer a reservation");this.acquireDecision(id);try{const item=this.get(id);this.assertVersion(item,expectedVersion);if(!["AWAITING_DECISION",...this.TABLE_FREE_WAITING_STATUSES].includes(item.status))this.fail("RESERVATION_NOT_AWAITING_DECISION","Reservation is not awaiting a decision");const minutes=this.settings().reservation.deferMinutes,base=new Date(item.effectiveReservationAt||item.reservedAt);item.effectiveReservationAt=new Date(base.getTime()+minutes*60000).toISOString();item.deferCount=Number(item.deferCount||0)+1;item.status="DEFERRED";this.timeline(item,"RESERVATION_DEFERRED",user.userId);this.save(item,user.userId);this.audit("RESERVATION_DEFERRED",user.userId,{reservationId:item.id,minutes});return item;}finally{this.decisionLocks.delete(id);} }
  checkIn(id,user) { const item=this.get(id);if(!["OWNER","MANAGER","CASHIER","STAFF"].includes(user.role))this.fail("FORBIDDEN","You cannot check in reservations");if(item.status!=="OPENED_WAITING_CHECK_IN")this.fail(item.status==="CHECKED_IN"?"RESERVATION_ALREADY_CHECKED_IN":"RESERVATION_NOT_WAITING_CHECK_IN","Reservation is not waiting for check-in");if(new Date(item.checkInDeadlineAt)<=this.now())this.fail("CHECK_IN_DEADLINE_EXPIRED","Check-in deadline has expired");item.status="CHECKED_IN";item.checkedInAt=this.stamp();item.customerArrivalConfirmed=true;this.timeline(item,"RESERVATION_CHECKED_IN",user.userId,{tableSessionId:item.tableSessionId});this.save(item,user.userId);this.audit("RESERVATION_CHECKED_IN",user.userId,{reservationId:item.id,tableId:item.assignedTableId,tableSessionId:item.tableSessionId});return item; }
  async noShow(id,user,internal=false) { const item=this.get(id);if(!internal&&!["OWNER","MANAGER"].includes(user.role))this.fail("FORBIDDEN","Only OWNER or MANAGER may mark no-show");if(item.status!=="OPENED_WAITING_CHECK_IN")this.fail(item.status==="NO_SHOW"?"RESERVATION_ALREADY_NO_SHOW":"RESERVATION_NOT_WAITING_CHECK_IN","Reservation is not waiting for check-in");const table=this.tables().find(x=>String(x.id)===String(item.assignedTableId));if(table)await this.relay(table,"off");await this.cancelSession(item.tableSessionId);item.status="NO_SHOW";item.noShowAt=this.stamp();item.checkInDeadlineAt=null;this.timeline(item,"NO_SHOW",user.userId);this.timeline(item,"SESSION_CLOSED",user.userId,{tableSessionId:item.tableSessionId});this.save(item,user.userId);let deposit=null;if(this.settings().reservation.autoForfeitNoShowDeposit)deposit=this.depositService.forfeitForReservation(item.id,user.userId);this.audit("RESERVATION_NO_SHOW_PROCESSED",user.userId,{reservationId:item.id,tableId:item.assignedTableId,depositId:deposit?.id||null});return item; }
  dashboard() { const day=bangkokDay(this.now()),reservations=this.repository.list(),deposits=this.depositService.list(),sum=(items,key="amountSatang")=>items.reduce((s,x)=>s+Number(x[key]||0),0);return {todayReservations:reservations.filter(x=>x.reservationDate===day).length,awaitingDecision:reservations.filter(x=>x.status==="AWAITING_DECISION").length,deferred:reservations.filter(x=>x.status==="DEFERRED").length,waitingQueue:reservations.filter(x=>x.status==="WAITING_TABLE").length,openedWaitingCheckIn:reservations.filter(x=>x.status==="OPENED_WAITING_CHECK_IN").length,checkedIn:reservations.filter(x=>x.status==="CHECKED_IN").length,todayNoShow:reservations.filter(x=>x.status==="NO_SHOW"&&bangkokDay(new Date(x.noShowAt))===day).length,outstandingDepositSatang:sum(deposits.filter(x=>["AVAILABLE","LOCKED"].includes(x.status))),noShowDepositRevenueSatang:sum(deposits.filter(x=>x.status==="FORFEITED"&&bangkokDay(new Date(x.forfeitedAt))===day))}; }
}
module.exports = { ReservationService, STATUSES };
